# Generated by Django 6.0.4 on 2026-04-30 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine_b2b', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerprofile',
            name='business_photo',
            field=models.ImageField(blank=True, help_text='Partner photo shown in confirmed customer itinerary.', null=True, upload_to='profiles/partners/'),
        ),
    ]
