# Generated by Django 6.0.4 on 2026-05-01 19:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine_b2b', '0002_partnerprofile_business_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerEarning',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('booking_item_id', models.CharField(db_index=True, max_length=100)),
                ('amount_gross', models.DecimalField(decimal_places=2, max_digits=12)),
                ('commission_rate', models.FloatField(default=0.15)),
                ('amount_net', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('paid', 'Paid')], default='pending', max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earnings', to='engine_b2b.partnerprofile')),
            ],
            options={
                'db_table': 'partner_earnings',
            },
        ),
        migrations.CreateModel(
            name='PartnerAvailabilitySlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('available', 'Available'), ('blocked', 'Blocked'), ('booked', 'Fully Booked')], default='available', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='engine_b2b.partnerprofile')),
            ],
            options={
                'db_table': 'partner_availability',
                'unique_together': {('partner', 'date')},
            },
        ),
    ]
