# Generated by Django 6.0.4 on 2026-04-26 16:31

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=100)),
                ('zone', models.CharField(choices=[('uttar', 'Uttar (North)'), ('poorab', 'Poorab (East)'), ('pashchim', 'Pashchim (West)'), ('dakshin', 'Dakshin (South)'), ('madhyam', 'Madhyam (Central)')], max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('image_url', models.URLField(blank=True, default='')),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('region_code', models.CharField(blank=True, default='', max_length=3)),
            ],
            options={
                'db_table': 'regions',
                'ordering': ['zone', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('node_type', models.CharField(choices=[('activity', 'Activity'), ('filler', 'Filler'), ('transit', 'Transit')], default='activity', max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('short_desc', models.CharField(blank=True, default='', max_length=500)),
                ('description', models.TextField(blank=True, default='')),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('altitude_m', models.IntegerField(default=0)),
                ('category', models.CharField(choices=[('adventure_sports', 'Adventure Sports'), ('camping', 'Camping'), ('cultural', 'Cultural'), ('food', 'Food'), ('heritage', 'Heritage'), ('hobbyist', 'Hobbyist'), ('meditation', 'Meditation'), ('photography', 'Photography'), ('rafting', 'Rafting'), ('rest', 'Rest'), ('transit', 'Transit'), ('trekking', 'Trekking'), ('water_sports', 'Water Sports'), ('wildlife', 'Wildlife')], max_length=30)),
                ('tone', models.CharField(choices=[('yin', 'Yin / Chill'), ('both', 'Both'), ('yang', 'Yang / Adventure')], default='both', max_length=10)),
                ('effort_score', models.FloatField(default=0.5)),
                ('duration_hrs', models.FloatField(default=1.0)),
                ('reward_score', models.FloatField(default=0.75)),
                ('reward_score_base', models.FloatField(default=0.75)),
                ('reward_score_max', models.FloatField(default=0.75)),
                ('recovery_coeff', models.FloatField(default=0.0)),
                ('significance_score', models.FloatField(default=0.5)),
                ('risk_tier', models.CharField(choices=[('casual', 'Casual'), ('moderate', 'Moderate'), ('high', 'High'), ('extreme', 'Extreme')], default='casual', max_length=20)),
                ('noc_required', models.BooleanField(default=False)),
                ('fitness_note', models.CharField(blank=True, default='', max_length=500)),
                ('seasonal_availability', models.JSONField(default=dict)),
                ('is_fixed_route', models.BooleanField(default=False)),
                ('time_of_day_sensitivity', models.BooleanField(default=False)),
                ('is_shiftable_anytime', models.BooleanField(default=False)),
                ('preferred_time_windows', models.JSONField(default=list)),
                ('buffer_before_mins', models.IntegerField(default=15)),
                ('buffer_after_mins', models.IntegerField(default=15)),
                ('allowance_time_mins', models.IntegerField(default=30)),
                ('has_time_exception', models.BooleanField(default=False)),
                ('exception_start_time', models.TimeField(blank=True, null=True)),
                ('time_exception_detail', models.JSONField(default=dict)),
                ('operating_months', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list)),
                ('functional_days', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list)),
                ('operating_hours', models.JSONField(default=dict)),
                ('holidays', models.JSONField(default=list)),
                ('tools', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list)),
                ('gear_class', models.IntegerField(default=0)),
                ('permit_required', models.BooleanField(default=False)),
                ('permit_type', models.CharField(blank=True, default='', max_length=100)),
                ('guide_mandatory', models.BooleanField(default=False)),
                ('dietary_support', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list)),
                ('price_from', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_filler', models.BooleanField(default=False)),
                ('content_approved', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activities', to='engine_b2c.region')),
            ],
            options={
                'db_table': 'activities',
                'ordering': ['region', 'category', 'name'],
            },
        ),
    ]
