# Generated by Django 6.0.4 on 2026-04-28 03:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine_b2c', '0002_externalapicredential_booking_bookinglineitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollabGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('created_by', models.CharField(max_length=100)),
                ('created_by_name', models.CharField(blank=True, default='', max_length=255)),
                ('region_id', models.CharField(blank=True, default='', max_length=100)),
                ('trip_start_date', models.DateField(blank=True, null=True)),
                ('trip_end_date', models.DateField(blank=True, null=True)),
                ('travel_style', models.FloatField(default=0.5)),
                ('season', models.CharField(default='summer', max_length=20)),
                ('itinerary_snapshot', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('forming', 'Forming'), ('confirmed', 'Confirmed'), ('travelling', 'Travelling'), ('completed', 'Completed'), ('disbanded', 'Disbanded')], default='forming', max_length=20)),
                ('max_members', models.PositiveIntegerField(default=10)),
                ('notes', models.TextField(blank=True, default='')),
                ('is_public', models.BooleanField(default=False)),
                ('public_note', models.CharField(blank=True, default='', max_length=255)),
                ('open_spots', models.PositiveIntegerField(default=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'collab_groups',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CollabMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sender_id', models.CharField(max_length=100)),
                ('sender_name', models.CharField(max_length=255)),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('system', 'System'), ('itinerary', 'Itinerary Update')], default='text', max_length=15)),
                ('content', models.TextField()),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='engine_b2c.collabgroup')),
            ],
            options={
                'db_table': 'collab_messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='CollabMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=150)),
                ('display_name', models.CharField(blank=True, default='', max_length=255)),
                ('role', models.CharField(choices=[('leader', 'Leader'), ('member', 'Member')], default='member', max_length=10)),
                ('status', models.CharField(choices=[('invited', 'Invited'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('removed', 'Removed')], default='invited', max_length=10)),
                ('booking_id', models.CharField(blank=True, default='', max_length=100)),
                ('invited_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('pickup_region', models.CharField(blank=True, default='', max_length=100)),
                ('pickup_city', models.CharField(blank=True, default='', max_length=100)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='engine_b2c.collabgroup')),
            ],
            options={
                'db_table': 'collab_members',
                'unique_together': {('group', 'user_id')},
            },
        ),
    ]
