# Generated by Django 6.0.4 on 2026-04-28 04:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine_b2c', '0003_collabgroup_collabmessage_collabmember'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(db_index=True, max_length=100)),
                ('notification_type', models.CharField(choices=[('booking_confirmed', 'Booking Confirmed'), ('booking_rejected', 'Booking Rejected'), ('booking_cancelled', 'Booking Cancelled'), ('booking_completed', 'Booking Completed'), ('partner_confirmed', 'Partner Confirmed Activity'), ('partner_rejected', 'Partner Rejected Activity'), ('partner_new_booking', 'New Booking (Partner)'), ('payment_success', 'Payment Successful'), ('refund_initiated', 'Refund Initiated'), ('refund_completed', 'Refund Completed'), ('advance_requested', 'Advance Payment Requested'), ('advance_paid', 'Advance Paid'), ('collab_invite', 'Collab Invite Received'), ('collab_member_joined', 'Member Joined Your Group'), ('collab_member_left', 'Member Left Your Group'), ('collab_itinerary_updated', 'Group Itinerary Updated'), ('disruption_alert', 'Travel Disruption Alert'), ('force_majeure', 'Force Majeure — Booking Cancelled'), ('system', 'System Message')], max_length=40)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('booking_id', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('action_url', models.CharField(blank=True, default='', max_length=500)),
                ('metadata', models.JSONField(default=dict)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('sent_whatsapp', models.BooleanField(default=False)),
                ('sent_email', models.BooleanField(default=False)),
                ('sent_push', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdvancePaymentRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('coordinator', 'Coordinator Created'), ('customer_self', 'Customer Self-Service')], default='coordinator', max_length=20)),
                ('coordinator_id', models.CharField(blank=True, default='', max_length=100)),
                ('coordinator_name', models.CharField(blank=True, default='', max_length=255)),
                ('hotel_name', models.CharField(max_length=255)),
                ('advance_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('reason', models.TextField(blank=True, default='')),
                ('razorpay_order_id', models.CharField(blank=True, default='', max_length=100)),
                ('razorpay_payment_id', models.CharField(blank=True, default='', max_length=100)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('forwarded_at', models.DateTimeField(blank=True, null=True)),
                ('forwarded_by', models.CharField(blank=True, default='', max_length=255)),
                ('forwarding_note', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Pending Customer Payment'), ('paid', 'Paid by Customer'), ('forwarded', 'Forwarded to Hotel'), ('confirmed', 'Hotel Confirmed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('customer_message', models.TextField(default='Please pay the advance to confirm your hotel booking.')),
                ('no_coordinator', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advance_requests', to='engine_b2c.booking')),
                ('line_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advance_requests', to='engine_b2c.bookinglineitem')),
            ],
            options={
                'db_table': 'advance_payment_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TripBuffer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('loaded_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('used_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('razorpay_order_id', models.CharField(blank=True, default='', max_length=100)),
                ('razorpay_payment_id', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(choices=[('unfunded', 'Unfunded'), ('funded', 'Funded'), ('partially_used', 'Partially Used'), ('exhausted', 'Exhausted'), ('refunded', 'Refunded')], default='unfunded', max_length=20)),
                ('funded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trip_buffer', to='engine_b2c.booking')),
            ],
            options={
                'db_table': 'trip_buffers',
            },
        ),
    ]
