# Generated by Django 6.0.4 on 2026-04-28 04:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine_b2c', '0004_notification_advancepaymentrequest_tripbuffer'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomAvailability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('partner_id', models.CharField(db_index=True, max_length=100)),
                ('room_id', models.CharField(db_index=True, max_length=100)),
                ('date', models.DateField(db_index=True)),
                ('total_rooms', models.PositiveIntegerField(default=1)),
                ('booked_rooms', models.PositiveIntegerField(default=0)),
                ('blocked_rooms', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_availability', to='engine_b2c.region')),
            ],
            options={
                'db_table': 'room_availability',
                'ordering': ['date'],
                'unique_together': {('partner_id', 'room_id', 'date')},
            },
        ),
    ]
