# Generated by Django 6.0.4 on 2026-04-28 07:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine_b2c', '0005_roomavailability'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoVoucher',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code_prefix', models.CharField(max_length=20)),
                ('code', models.CharField(blank=True, db_index=True, max_length=30, unique=True)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage (%)'), ('fixed_amount', 'Fixed Amount (₹)')], default='percentage', max_length=15)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=8)),
                ('max_discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('min_booking_amount', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('valid_from', models.DateTimeField()),
                ('valid_until', models.DateTimeField()),
                ('usage_limit_per_day', models.PositiveIntegerField(default=0)),
                ('total_usage_limit', models.PositiveIntegerField(default=0)),
                ('total_used', models.PositiveIntegerField(default=0)),
                ('used_today', models.PositiveIntegerField(default=0)),
                ('last_reset_date', models.CharField(blank=True, default='', max_length=10)),
                ('restricted_regions', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'promo_vouchers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VoucherRedemption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=100)),
                ('booking_total_before', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_applied', models.DecimalField(decimal_places=2, max_digits=10)),
                ('booking_total_after', models.DecimalField(decimal_places=2, max_digits=10)),
                ('redeemed_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='voucher_redemptions', to='engine_b2c.booking')),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='redemptions', to='engine_b2c.promovoucher')),
            ],
            options={
                'db_table': 'voucher_redemptions',
            },
        ),
    ]
