# Generated by Django 6.0.4 on 2026-04-28 12:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine_b2c', '0006_promovoucher_voucherredemption'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoordinatorSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(db_index=True, max_length=100)),
                ('booking_id', models.CharField(blank=True, default='', max_length=100)),
                ('channel', models.CharField(choices=[('app', 'In-App'), ('whatsapp', 'WhatsApp')], default='app', max_length=10)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('was_escalated', models.BooleanField(default=False)),
                ('escalation_reason', models.CharField(blank=True, default='maintenance', max_length=255)),
            ],
            options={
                'db_table': 'coordinator_sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='CoordinatorMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sender', models.CharField(choices=[('user', 'User'), ('bot', 'Bot'), ('coordinator', 'Coordinator')], max_length=15)),
                ('text', models.TextField()),
                ('intent_hint', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='engine_b2c.coordinatorsession')),
            ],
            options={
                'db_table': 'coordinator_messages',
                'ordering': ['created_at'],
            },
        ),
    ]
