# Generated by Django 6.0.4 on 2026-04-28 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine_b2c', '0007_coordinatorsession_coordinatormessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='min_age',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
