# Generated by Django 6.0.4 on 2026-05-01 19:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine_b2c', '0008_activity_min_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiscService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('category', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('image_url', models.URLField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'misc_services',
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('short_desc', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, default='')),
                ('category', models.CharField(choices=[('adventure_sports', 'Adventure Sports'), ('camping', 'Camping'), ('cultural', 'Cultural'), ('food', 'Food'), ('heritage', 'Heritage'), ('hobbyist', 'Hobbyist'), ('meditation', 'Meditation'), ('photography', 'Photography'), ('rafting', 'Rafting'), ('rest', 'Rest'), ('transit', 'Transit'), ('trekking', 'Trekking'), ('water_sports', 'Water Sports'), ('wildlife', 'Wildlife')], max_length=30)),
                ('days_count', models.PositiveIntegerField(default=1)),
                ('per_person_estimate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('image_url', models.URLField(blank=True, default='')),
                ('itinerary_template', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('is_coming_soon', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'packages',
                'ordering': ['-created_at'],
            },
        ),
    ]
