# Generated by Django 6.0.4 on 2026-04-26 16:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='DietaryMode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('enum_value', models.CharField(choices=[('no_restriction', 'No Restriction'), ('vegetarian', 'Vegetarian'), ('non_pungent', 'Non Pungent')], max_length=30, unique=True)),
                ('canonical_text', models.TextField()),
            ],
            options={
                'db_table': 'dietary_modes',
            },
        ),
        migrations.CreateModel(
            name='EngineConfig',
            fields=[
                ('id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('w_reward', models.FloatField(default=0.4)),
                ('w_arc', models.FloatField(default=0.25)),
                ('w_novelty', models.FloatField(default=0.2)),
                ('w_weather', models.FloatField(default=0.15)),
                ('path_efficiency_floor', models.FloatField(default=0.65)),
                ('engine_shortlist_n', models.IntegerField(default=5)),
                ('yang_buffer_threshold', models.FloatField(default=0.5)),
                ('beam_width', models.IntegerField(default=50)),
                ('annealing_timeout_s', models.IntegerField(default=30)),
                ('transit_threshold_min', models.IntegerField(default=45)),
                ('day_start_time', models.TimeField(default='07:00')),
                ('rest_trigger_time', models.TimeField(default='18:00')),
                ('dinner_as_node', models.BooleanField(default=False)),
                ('high_risk_threshold', models.FloatField(default=0.7)),
                ('noc_risk_threshold', models.FloatField(default=0.65)),
                ('noc_altitude_threshold', models.IntegerField(default=4000)),
                ('rf_n_trees', models.IntegerField(default=100)),
                ('rf_max_depth', models.IntegerField(default=10)),
                ('rf_min_samples_leaf', models.IntegerField(default=5)),
                ('filler_rate_min', models.FloatField(default=0.1)),
                ('filler_rate_max', models.FloatField(default=0.18)),
                ('default_guides_per_vehicle', models.IntegerField(default=1)),
                ('default_coordinators_per_group', models.IntegerField(default=1)),
                ('assistance_tier_fees', models.JSONField(default=dict)),
                ('coverage_floor', models.JSONField(default=dict)),
                ('custom_coefficients', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'engine_config',
            },
        ),
        migrations.CreateModel(
            name='RegionConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, choices=[('GHW', 'Garhwal'), ('KMN', 'Kumaon'), ('HPS', 'HP Spiti/Manali'), ('HSD', 'HP Shimla/Kinnaur'), ('LDK', 'Ladakh/Kashmir'), ('RAJ', 'Rajasthan'), ('PNJ', 'Punjab'), ('HRY', 'Haryana'), ('ASM', 'Assam'), ('MEG', 'Meghalaya'), ('ARP', 'Arunachal'), ('SKM', 'Sikkim'), ('NEM', 'NE Mixed')], max_length=3, null=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('coverage_floor', models.JSONField(default=dict)),
                ('required_categories', models.JSONField(default=list)),
                ('default_season', models.CharField(default='summer', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('lat_min', models.FloatField(blank=True, null=True)),
                ('lat_max', models.FloatField(blank=True, null=True)),
                ('lon_min', models.FloatField(blank=True, null=True)),
                ('lon_max', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'region_config',
            },
        ),
        migrations.CreateModel(
            name='ScoringModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score_type', models.CharField(choices=[('effort_score', 'Effort Score'), ('reward_score', 'Reward Score'), ('recovery_coeff', 'Recovery Coefficient'), ('significance_score', 'Significance Score'), ('tone', 'Tone Classification'), ('is_filler', 'Is Filler Classification'), ('quality_score', 'Quality Score')], max_length=30, unique=True)),
                ('model_json', models.TextField(default='{}')),
                ('is_trained', models.BooleanField(default=False)),
                ('training_samples', models.IntegerField(default=0)),
                ('last_trained_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'scoring_models',
            },
        ),
        migrations.CreateModel(
            name='ScoringTrainingSample',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('features', models.JSONField()),
                ('effort_score', models.FloatField(blank=True, null=True)),
                ('reward_score', models.FloatField(blank=True, null=True)),
                ('recovery_coeff', models.FloatField(blank=True, null=True)),
                ('significance_score', models.FloatField(blank=True, null=True)),
                ('tone', models.CharField(blank=True, max_length=10, null=True)),
                ('is_filler_label', models.CharField(blank=True, max_length=10, null=True)),
                ('quality_score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'scoring_training_samples',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('mobile', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('nationality', models.CharField(default='Indian', max_length=100)),
                ('roles', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('guest_token', models.CharField(blank=True, max_length=255, null=True)),
                ('username', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='AdminAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(max_length=100)),
                ('target_type', models.CharField(max_length=100)),
                ('target_id', models.CharField(max_length=255)),
                ('before_state', models.JSONField(blank=True, null=True)),
                ('after_state', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('celery_task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'admin_actions',
            },
        ),
        migrations.CreateModel(
            name='PartnerService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service_type', models.CharField(choices=[('hotel', 'Hotel'), ('guide', 'Guide'), ('cab', 'Cab'), ('transport', 'Transport'), ('vehicle_rental', 'Vehicle Rental'), ('misc_activity_provider', 'Misc Activity Provider')], max_length=30)),
                ('license_document', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], default='pending', max_length=20)),
                ('failure_count', models.IntegerField(default=0)),
                ('push_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'partner_services',
                'unique_together': {('user', 'service_type')},
            },
        ),
    ]
