# Generated by Django 6.0.4 on 2026-04-28 02:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine_meta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='engineconfig',
            name='bookingcom_affiliate',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='engineconfig',
            name='bookingcom_api_key',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='engineconfig',
            name='bookingcom_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='ThirdPartyAPIConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('api_key', models.CharField(choices=[('razorpay', 'Razorpay'), ('redbus', 'RedBus'), ('abhibus', 'AbhiBus'), ('irctc', 'IRCTC (Train)'), ('bookingcom', 'Booking.com'), ('uidai', 'UIDAI Aadhaar'), ('mrz', 'MRZ Passport Scanner'), ('whatsapp', 'WhatsApp Business API'), ('osrm', 'OSRM Routing (self-hosted)')], max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=False)),
                ('is_coming_soon', models.BooleanField(default=False)),
                ('coming_soon_note', models.CharField(blank=True, default='', max_length=255)),
                ('credentials', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('unconfigured', 'Unconfigured'), ('configured', 'Configured'), ('live', 'Live'), ('error', 'Error'), ('coming_soon', 'Coming Soon'), ('disabled', 'Disabled')], default='unconfigured', max_length=20)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('docs_url', models.URLField(blank=True, default='')),
                ('internal_notes', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_config_edits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Third-Party API Config',
                'verbose_name_plural': 'Third-Party API Configs',
                'db_table': 'third_party_api_configs',
            },
        ),
    ]
