# Generated by Django 6.0.4 on 2026-04-28 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine_meta', '0002_engineconfig_bookingcom_affiliate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='engineconfig',
            name='coordinator_offline_msg',
            field=models.CharField(default='Our AI assistant is currently under maintenance. A coordinator will reach out to you shortly if needed.', max_length=500),
        ),
        migrations.AddField(
            model_name='engineconfig',
            name='coordinator_storage_quota_mb',
            field=models.PositiveIntegerField(default=500),
        ),
        migrations.AddField(
            model_name='engineconfig',
            name='is_coordinator_active',
            field=models.BooleanField(default=False),
        ),
    ]
