# Generated by Django 6.0.4 on 2026-04-30 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine_meta', '0003_engineconfig_coordinator_offline_msg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, help_text='Customer profile photo for partner ID verification.', null=True, upload_to='profiles/customers/'),
        ),
    ]
